"""migration

Revision ID: 163ce10f4297
Revises: b202d46911a1
Create Date: 2021-11-11 19:39:27.279924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163ce10f4297'
down_revision = 'b202d46911a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_item', sa.Column('estimated_total', sa.Float(), nullable=True))
    with op.batch_alter_table('budget_item') as batch_op:
      batch_op.drop_column('estimate_total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_item', sa.Column('estimate_total', sa.FLOAT(), nullable=True))
    op.drop_column('budget_item', 'estimated_total')
    # ### end Alembic commands ###
