"""initial migration

Revision ID: b202d46911a1
Revises: 
Create Date: 2021-11-11 19:08:33.714582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b202d46911a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_item') as batch_op:
      batch_op.drop_column('estimated_total')
    with op.batch_alter_table('budget_item') as batch_op:
      batch_op.drop_column( 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_item', sa.Column('price', sa.FLOAT(), nullable=True))
    op.add_column('budget_item', sa.Column('estimated_total', sa.FLOAT(), nullable=True))
    op.drop_column('budget_item', 'estimate_total')
    # ### end Alembic commands ###
